-- Clinical data table counts

select 'person' as tablename, count_big(*) as count, count(distinct person_id) AS personcount, 100 * round(cast(count(distinct person_id) as number(10)) / (SELECT count(distinct person_id) FROM @cdmDatabaseSchema.person), 3) as personcountrate,100 * round(cast(count(distinct person_id) as number(10)) / (SELECT count(distinct person_id) as observationcountrate FROM @cdmDatabaseSchema.observation_period), 3) as observedcountrate from @cdmDatabaseSchema.person group by 1
UNION
select 'care_site' as tablename, count_big(*) as count, NULL AS personcount, NULL as personcountrate, NULL as observedcountrate  from @cdmDatabaseSchema.care_site group by 1
UNION
select 'condition_era' as tablename, count_big(*) as count, count(distinct person_id) AS personcount, 100 *  round(cast(count(distinct person_id) as number(10)) / (SELECT count(distinct person_id) FROM @cdmDatabaseSchema.person), 3) as personcountrate,100 * round(cast(count(distinct person_id) as number(10)) / (SELECT count(distinct person_id) as observationcountrate FROM @cdmDatabaseSchema.observation_period), 3) as observedcountrate  from @cdmDatabaseSchema.condition_era group by 1
UNION
select 'condition_occurrence' as tablename, count_big(*) as count, count(distinct person_id) AS personcount,100 *  round(cast(count(distinct person_id) as number(10)) / (SELECT count(distinct person_id) FROM @cdmDatabaseSchema.person), 3) as personcountrate,100 * round(cast(count(distinct person_id) as number(10)) / (SELECT count(distinct person_id) as observationcountrate FROM @cdmDatabaseSchema.observation_period), 3) as observedcountrate from @cdmDatabaseSchema.condition_occurrence group by 1
UNION
select 'drug_exposure' as tablename, count_big(*) as count, count(distinct person_id) AS personcount,100 *  round(cast(count(distinct person_id) as number(10)) / (SELECT count(distinct person_id) FROM @cdmDatabaseSchema.person), 3) as personcountrate,100 * round(cast(count(distinct person_id) as number(10)) / (SELECT count(distinct person_id) as observationcountrate FROM @cdmDatabaseSchema.observation_period), 3) as observedcountrate  from @cdmDatabaseSchema.drug_exposure group by 1
UNION
select 'cost' as tablename, count_big(*) as count, NULL AS personcount, NULL as personcountrate, NULL as observedcountrate from @cdmDatabaseSchema.cost group by 1
UNION
select 'death' as tablename, count_big(*) as count, count(distinct person_id) AS personcount, 100 * round(cast(count(distinct person_id) as number(10)) / (SELECT count(distinct person_id) FROM @cdmDatabaseSchema.person), 3) as personcountrate, 100 *round(cast(count(distinct person_id) as number(10)) / (SELECT count(distinct person_id) as observationcountrate FROM @cdmDatabaseSchema.observation_period), 3) as observedcountrate  from @cdmDatabaseSchema.death group by 1
UNION
select 'device_exposure' as tablename, count_big(*) as count, count(distinct person_id) AS personcount, 100 * round(cast(count(distinct person_id) as number(10)) / (SELECT count(distinct person_id) FROM @cdmDatabaseSchema.person), 3) as personcountrate, 100 *round(cast(count(distinct person_id) as number(10)) / (SELECT count(distinct person_id) as observationcountrate FROM @cdmDatabaseSchema.observation_period), 3) as observedcountrate  from @cdmDatabaseSchema.device_exposure group by 1
UNION
select 'dose_era' as tablename, count_big(*) as count, count(distinct person_id) AS personcount, 100 * round(cast(count(distinct person_id) as number(10)) / (SELECT count(distinct person_id) FROM @cdmDatabaseSchema.person), 3) as personcountrate, 100 *round(cast(count(distinct person_id) as number(10)) / (SELECT count(distinct person_id) as observationcountrate FROM @cdmDatabaseSchema.observation_period), 3) as observedcountrate  from @cdmDatabaseSchema.dose_era group by 1
UNION
select 'drug_era' as tablename, count_big(*) as count, count(distinct person_id) AS personcount, 100 * round(cast(count(distinct person_id) as number(10)) / (SELECT count(distinct person_id) FROM @cdmDatabaseSchema.person), 3) as personcountrate, 100 *round(cast(count(distinct person_id) as number(10)) / (SELECT count(distinct person_id) as observationcountrate FROM @cdmDatabaseSchema.observation_period), 3) as observedcountrate  from @cdmDatabaseSchema.drug_era group by 1
UNION
select 'location' as tablename, count_big(*) as count, NULL AS personcount, NULL as personcountrate, NULL as observedcountrate  from @cdmDatabaseSchema.location group by 1
UNION
select 'measurement' as tablename, count_big(*) as count, count(distinct person_id) AS personcount, 100 * round(cast(count(distinct person_id) as number(10)) / (SELECT count(distinct person_id) FROM @cdmDatabaseSchema.person), 3) as personcountrate, 100 *round(cast(count(distinct person_id) as number(10)) / (SELECT count(distinct person_id) as observationcountrate FROM @cdmDatabaseSchema.observation_period), 3) as observedcountrate  from @cdmDatabaseSchema.measurement group by 1
UNION
select 'note' as tablename, count_big(*) as count, count(distinct person_id) AS personcount, 100 * round(cast(count(distinct person_id) as number(10)) / (SELECT count(distinct person_id) FROM @cdmDatabaseSchema.person), 3) as personcountrate, 100 *round(cast(count(distinct person_id) as number(10)) / (SELECT count(distinct person_id) as observationcountrate FROM @cdmDatabaseSchema.observation_period), 3) as observedcountrate  from @cdmDatabaseSchema.note group by 1
UNION
select 'observation' as tablename, count_big(*) as count, count(distinct person_id) AS personcount, 100 * round(cast(count(distinct person_id) as number(10)) / (SELECT count(distinct person_id) FROM @cdmDatabaseSchema.person), 3) as personcountrate, 100 *round(cast(count(distinct person_id) as number(10)) / (SELECT count(distinct person_id) as observationcountrate FROM @cdmDatabaseSchema.observation_period), 3) as observedcountrate  from @cdmDatabaseSchema.observation group by 1
UNION
select 'observation_period' as tablename, count_big(*) as count, count(distinct person_id) AS personcount, 100 * round(cast(count(distinct person_id) as number(10)) / (SELECT count(distinct person_id) FROM @cdmDatabaseSchema.person), 3) as personcountrate, 100 *round(cast(count(distinct person_id) as number(10)) / (SELECT count(distinct person_id) as observationcountrate FROM @cdmDatabaseSchema.observation_period), 3) as observedcountrate  from @cdmDatabaseSchema.observation_period group by 1
UNION
select 'payer_plan_period' as tablename, count_big(*) as count, count(distinct person_id) AS personcount, 100 * round(cast(count(distinct person_id) as number(10)) / (SELECT count(distinct person_id) FROM @cdmDatabaseSchema.person), 3) as personcountrate, 100 *round(cast(count(distinct person_id) as number(10)) / (SELECT count(distinct person_id) as observationcountrate FROM @cdmDatabaseSchema.observation_period), 3) as observedcountrate  from @cdmDatabaseSchema.payer_plan_period group by 1
UNION
select 'procedure_occurrence' as tablename, count_big(*) as count, count(distinct person_id) AS personcount, 100 * round(cast(count(distinct person_id) as number(10)) / (SELECT count(distinct person_id) FROM @cdmDatabaseSchema.person), 3) as personcountrate, 100 *round(cast(count(distinct person_id) as number(10)) / (SELECT count(distinct person_id) as observationcountrate FROM @cdmDatabaseSchema.observation_period), 3) as observedcountrate  from @cdmDatabaseSchema.procedure_occurrence group by 1
UNION
select 'provider' as tablename, count_big(*) as count, NULL AS personcount, NULL as personcountrate, NULL as observedcountrate from @cdmDatabaseSchema.provider group by 1
UNION
select 'specimen' as tablename, count_big(*) as count, count(distinct person_id) AS personcount, 100 * round(cast(count(distinct person_id) as number(10)) / (SELECT count(distinct person_id) FROM @cdmDatabaseSchema.person), 3) as personcountrate, 100 *round(cast(count(distinct person_id) as number(10)) / (SELECT count(distinct person_id) as observationcountrate FROM @cdmDatabaseSchema.observation_period), 3) as observedcountrate  from @cdmDatabaseSchema.specimen group by 1
UNION
select 'visit_details' as tablename, count_big(*) as count, count(distinct person_id) AS personcount,100 *  round(cast(count(distinct person_id) as number(10)) / (SELECT count(distinct person_id) FROM @cdmDatabaseSchema.person), 3) as personcountrate,100 * round(cast(count(distinct person_id) as number(10)) / (SELECT count(distinct person_id) as observationcountrate FROM @cdmDatabaseSchema.observation_period), 3) as observedcountrate  from @cdmDatabaseSchema.visit_detail group by 1
UNION
select 'visit_occurrence' as tablename, count_big(*) as count, count(distinct person_id) AS personcount, 100 * round(cast(count(distinct person_id) as number(10)) / (SELECT count(distinct person_id) FROM @cdmDatabaseSchema.person), 3) as personcountrate, 100 *round(cast(count(distinct person_id) as number(10)) / (SELECT count(distinct person_id) as observationcountrate FROM @cdmDatabaseSchema.observation_period), 3) as observedcountrate  from @cdmDatabaseSchema.visit_occurrence group by 1
